README update and sync-*.yml "fix"
snapcrafters/jenkins pull request #51
Opened 2023-12-11 17:23 UTC by kz6fittycent

- Updated README to match `signal-desktop`
  - Updated `sync-version-with-upstream.yml` - seems to be an indent causing an issue, as the script is working locally

2023-12-11 18:39 UTC, kz6fittycent commented
If there are anymore contributors to the snap that we want to list, please provide that list of names here and I'll add them with another commit. TY.

2023-12-12 20:40 UTC, merlijn-sebrechts requested changes
In addition to the comments above: You should add a blank line after every heading. Example:

```md
## License

The license of both the build files in this repository and Jenkins itself is the [MIT License](https://github.com/jenkinsci/jenkins/blob/master/LICENSE.txt)
```

2023-12-12 20:40 UTC, merlijn-sebrechts commented on README.md
> +<p align="center"><b>This is the snap for Jenkins, the leading open-source automation server</b>. It is a community-maintained package to easily install Jenkins on Ubuntu, Fedora, Debian and other ma
```suggestion
<p align="center"><b>This is the snap for Jenkins</b>. It is a community-maintained package to easily install Jenkins on Ubuntu, Fedora, Debian and other major Linux distributions. It is available in the Snap Store, Ubuntu Software, and a number of other applications.</p>
```

2023-12-12 20:40 UTC, merlijn-sebrechts commented on README.md
> -    xdg-open http://localhost:8080
Leave this command, it's useful

2023-12-12 20:40 UTC, merlijn-sebrechts commented on README.md
> -    cat config.xml | sudo /snap/bin/jenkins.config
We shouldn't remove this info, imo. Put it under its own headline after `## Install`. Something like `## Snap Configuration`

2023-12-12 20:40 UTC, merlijn-sebrechts commented on README.md
> +- [@merlijn-sebrechts](https://github.com/merlijn-sebrechts/)
I don't think you need to add me. This is all yours ;)

2023-12-13 02:41 UTC, kz6fittycent commented
I've addressed those various issues. Thanks for catching them.

2023-12-13 08:11 UTC, merlijn-sebrechts approved these changes
LGTM!

2023-12-13 08:12 UTC, merged